<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.716" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2024-12-12T20:30:15" tests="0" file="cypress\e2e\tarea.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Tareas App" timestamp="2024-12-12T20:30:15" tests="2" time="1.713" failures="2">
    <testcase name="Tareas App Debería mostrar la lista de tareas" time="0.000" classname="Debería mostrar la lista de tareas">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:4200/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:4200

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:4200/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:4200

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
    at <unknown> (http://localhost:52089/__cypress/runner/cypress_runner.js:131479:74)
    at visitFailedByErr (http://localhost:52089/__cypress/runner/cypress_runner.js:130878:12)
    at <unknown> (http://localhost:52089/__cypress/runner/cypress_runner.js:131478:11)
    at tryCatcher (http://localhost:52089/__cypress/runner/cypress_runner.js:1830:23)
    at Promise._settlePromiseFromHandler (http://localhost:52089/__cypress/runner/cypress_runner.js:1542:31)
    at Promise._settlePromise (http://localhost:52089/__cypress/runner/cypress_runner.js:1599:18)
    at Promise._settlePromise0 (http://localhost:52089/__cypress/runner/cypress_runner.js:1644:10)
    at Promise._settlePromises (http://localhost:52089/__cypress/runner/cypress_runner.js:1720:18)
    at _drainQueueStep (http://localhost:52089/__cypress/runner/cypress_runner.js:2430:12)
    at _drainQueue (http://localhost:52089/__cypress/runner/cypress_runner.js:2423:9)
    at Async._drainQueues (http://localhost:52089/__cypress/runner/cypress_runner.js:2439:5)
    at Async.drainQueues (http://localhost:52089/__cypress/runner/cypress_runner.js:2309:14)
From Your Spec Code:
    at Context.eval (webpack://sistemita-tareas/./cypress/e2e/tarea.cy.js:3:9)

From Node.js Internals:
  Error: connect ECONNREFUSED 127.0.0.1:4200
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)]]></failure>
    </testcase>
    <testcase name="Tareas App Debería agregar una nueva tarea" time="0.000" classname="Debería agregar una nueva tarea">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:4200/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:4200

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:4200/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:4200

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
    at <unknown> (http://localhost:52089/__cypress/runner/cypress_runner.js:131479:74)
    at visitFailedByErr (http://localhost:52089/__cypress/runner/cypress_runner.js:130878:12)
    at <unknown> (http://localhost:52089/__cypress/runner/cypress_runner.js:131478:11)
    at tryCatcher (http://localhost:52089/__cypress/runner/cypress_runner.js:1830:23)
    at Promise._settlePromiseFromHandler (http://localhost:52089/__cypress/runner/cypress_runner.js:1542:31)
    at Promise._settlePromise (http://localhost:52089/__cypress/runner/cypress_runner.js:1599:18)
    at Promise._settlePromise0 (http://localhost:52089/__cypress/runner/cypress_runner.js:1644:10)
    at Promise._settlePromises (http://localhost:52089/__cypress/runner/cypress_runner.js:1720:18)
    at _drainQueueStep (http://localhost:52089/__cypress/runner/cypress_runner.js:2430:12)
    at _drainQueue (http://localhost:52089/__cypress/runner/cypress_runner.js:2423:9)
    at Async._drainQueues (http://localhost:52089/__cypress/runner/cypress_runner.js:2439:5)
    at Async.drainQueues (http://localhost:52089/__cypress/runner/cypress_runner.js:2309:14)
From Your Spec Code:
    at Context.eval (webpack://sistemita-tareas/./cypress/e2e/tarea.cy.js:8:9)

From Node.js Internals:
  Error: connect ECONNREFUSED 127.0.0.1:4200
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)]]></failure>
    </testcase>
  </testsuite>
</testsuites>